### PR TITLE
Changes the require to the correct sprocket gem

### LINKED ISSUE #273: Updating 6.5.1.0 require 'sprockets/es6' isn't working have to change to require 'sprockets/rails'
When I updated to 6.5.1.0 and then start my rails sever I get 
```
/lib/ruby/gems/2.3.0/gems/foundation-rails-6.5.1.0/lib/foundation-rails.rb:2:in `require': cannot load such file -- sprockets/es6 (LoadError)
```

 to fix this I had to change the require to
```
 require 'sprockets/rails' 
```

### PR DESCRIPTION
**Pull request by brianmcoates**
This will fix the issue that breaks everything when trying to start your rails server. I have created an issue as well that this would close #273. I saw another fix was to add sprockets es6 to the gem file as well if that is the desired fix I can submit a pull request to update the documentation.

### CODE REVIEW

**Comment by khiet** [comment]
Hi @ncoden,

I see three options.

⚠️ I don't know what `sprockets-es6` for.

1. Update README to let users know `gem 'sprockets-es6'` has to be added to their `Gemfile`.

2. Add back `sprockets-es6` in the gemspec file so that it gets installed as a dependency.

3. if `sprockets-es6` is an unnecessary dependency for this gem, [these gemfiles](https://github.com/zurb/foundation-rails/search?q=sprockets-es6&unscoped_q=sprockets-es6) need to be cleaned up and @brianmcoates's fix is nice since Rails already comes with `sprockets-rails`.

My preference is 2.

**Comment by brianmcoates** [comment]
@ncoden after talking to my team here we found this https://github.com/zurb/foundation-rails/commit/a6c927db5f604d8d3e2e741389455b69d4c7aff2#diff-44263267796d33ed2765ce27a5ba5f3c What is happening when people bundle install bundle doesn't know what the dependencies are so we need to add them back in. I have updated the pull request to do that.

**Comment by ncoden** [comment]
@khiet @brianmcoates Thanks a lot for the explanations!

I made a mistake, I am sorry. Now I understand better how gemspec files are used. The pull request looks good to me now, but I'm waiting for the opinoin of @rafibomb's Rails engineers to merge it.

**Comment by brianmcoates** [comment]
@ncoden No worries man it happens to everyone. :) Looking forward to hearing back from your guys rails engineer.

**Comment by brianmcoates** [comment]
@ncoden have you guys had a chance to talk to your rails eng?

**Comment by ncoden** [comment]
@rafibomb

**Comment by patricklindsay** [comment]
Where is this Rails engineer at @rafibomb @ncoden  ? :)

**Comment by ncoden** [comment]
I removed the upper limit for `sass` (`foundation-sites` support all latest Sass versions) and regenerated the lockfiles.

**Pull request merged**
