### PR TITLE
Adding Foundation 6 Assets + Creating Rake Task

### PR DESCRIPTION
**Pull request by arthurzurb**
Updating GEM to use Foundation for Sites 6 assets.

We have removed Modernizr from F6 so I reflected that in the layout & generator etc.
We removed update-gem.sh file & created a Rake task based on @mehlah PR from Sites.
Small update to the README - taking out Modernizr for manual installation.

### CODE REVIEW

**Comment by mehlah** [comment]
@arthurzurb awesome :dancer: 
Let me know if you need any help with this.
Aside, I added last year some specs to ensure everything is still working fine for new releases https://github.com/zurb/foundation-rails/pull/120.
Do you want to enable Travis builds for it? I already wrote a `.travis.yml` file.
I could continue working on this again to have a better build process

**Comment by arthurzurb** [comment]
@mehlah That would be awesome, We were talking about getting travis in here as well. Whenever you are able to, just make a PR and we can get that in. Thanks so much!

**Comment by mehlah** [comment]
@arthurzurb I already did at #120 which is merged to master ;-)
You just have to enable Travis fro this repo (I don't have the rights for it)
screen shot 2016-01-13 at 01 35 30

**Comment by arthurzurb** [comment]
@mehlah Ah! Amazing haha. I will get to that in the morning. Thanks a bunch! Cheers!

**Pull request merged**
