### PR TITLE
Fix dropdown menu always open on flex mode

### PR DESCRIPTION
**Pull request by hapiben**
Adding the fix from this PR https://github.com/zurb/foundation-sites-template/pull/10.

### CODE REVIEW

**Comment by javierjulio** [comment]
@hapiben can you please rebase and push again to have Travis rebuild? I've had the same issue with the latest release of foundation-rails where flex mode is globally set and you are right. The drop down menus (top bar in my case) is always expanded. This does fix it.

**Comment by hapiben** [comment]
Hi @javierjulio done. Thanks!

**Comment by javierjulio** [comment]
@hapiben thanks! 👏🏻❤️

@kball this has been rebased and travis is now passing. This PR does fix the issue at hand and was also merged into the foundation sites template project.

**Comment by khiet** [comment]
What are we waiting to merge this in? I had the same problem and this fixed perfectly for me too.

**Pull request closed without merging**
