### PR TITLE
Upgrade to foundation-sites 6.3.1

### PR DESCRIPTION
**Pull request by Yanchek99**
This is to update the gem to the latest released version. [foundation-sites 6.3.1](https://github.com/zurb/foundation-sites/releases/tag/6.3.1)

### CODE REVIEW

**Comment by Yanchek99** [comment]
This fix actually does pass tests however Travis is failing due to https://github.com/zurb/foundation-rails/issues/220

**Comment by Yanchek99** [comment]
Hey @kball, Was wondering if it is possible to get this in soon.

**Comment by bousquet** [comment]
We would like to get this version too.  There are some bugs on mobile devices that 6.3.1 will fix for us.

**Comment by kball** [comment]
Sorry for the delay on this - merged and published!

**Pull request merged**
