### PR TITLE
chore: add support for multiple import solutions of JavaScript assets

### PR DESCRIPTION
**Pull request by ncoden**
This PR improve the way the sprockets file `foundation.js` is handled and make JavaScript assets importable by two differents ways according to the needs:
* By the main Foundation file `foundation.js` (or `foundation.min.js`)
* By all or some plugins `foundation.[plugin].js` (or `foundation.[plugin].min.js`)

### Changes:
* Make `foundation.js` a static asset and rename it to `foundation.sprockets.js`
  As a precise import order must be kept, "foundation.js" sprocket file cannot be dynamically generated.
* Add warning message on assets update to manually update `foundation.sprockets.js`
* Move plugins files to "vendor/assets/js/plugins"
* Add main Foundation distribution file `foundation.js` to assets
* Add main and plugins minified files `*.min.js` to assets
See commits descriptions for more informations.

### Others changes:
* Import responsive menus in last in `foundation.sprockets.js` as they require others menus.

See https://github.com/zurb/foundation-rails/pull/257 (@patricklindsay)

### CODE REVIEW

**Comment by ncoden** [comment]
@patricklindsay Could you review this ?

**Comment by ncoden** [comment]
Poke @DanielRuf too.

**Comment by ncoden** [comment]
Note: tests were already failing before this PR.

**Comment by DanielRuf** [comment]
> Note: tests were already failing before this PR.

Should be easy to solve. It's many years since I worked with RoR for the last time.
Not sure if I can properly test this.

**Comment by ncoden** [comment]
@DanielRuf See https://github.com/zurb/foundation-rails/issues/259

**Comment by patricklindsay** [comment]
My bad just seen this but looks good!

**Pull request merged**
