### PR TITLE
Upgrade to 6.4.3

### PR DESCRIPTION
**Pull request by chrisfinne**
Not sure if I did this right, but...

### CODE REVIEW

**Comment by patricklindsay** [comment]
Can anyone at Zurb look at this? Be great to get a release for 6.4.3 within this gem. Standalone was released nearly 6 months ago.

@rafibomb @kball (?)

**Comment by ncoden** [comment]
I updated the `_settings.scss` files in `/templates`

**Comment by MicahBrown** [comment]
@ncoden Thanks for getting this merged! Could you publish the new version to rubygems.org?

**Comment by ncoden** [comment]
@MicahBrown As soon as I can ;)

**Pull request merged**
