### PR TITLE
Update assets to 5.5.1

### PR DESCRIPTION
**Pull request by yllieth**
Any change in this PR are due to the execution of modified `update-gem.sh` script.

Please note changes I made in this file:
- removed useless `vendor/assets/_settings.scss` ; the one really used (in https://github.com/zurb/foundation-rails/blob/master/lib/foundation/rails/generators/install_generator.rb#L18) is `vendor/assets/stylesheets/foundation/_settings.scss`
- fixed path where scss files are pasted to `bower_components/foundation/scss/*` instead of `bower_components/foundation/scss/` (missing *)
- added automatic generation of `foundations.js` file which contains require instruction for rails

### CODE REVIEW

**Comment by mehlah** [comment]
This looks great to me :blue_heart:
@arthurzurb [bumped](https://github.com/zurb/foundation-rails/commit/09cde4ddd6135e63bda773f2267b7eacb97e3fff) the version number to 5.5.1 but the assets have not been updated.
5.5.1.1 gem should be pushed soon

**Comment by mehlah** [comment]
@arthurzurb I just updated the assets for 5.5.1, bumped the gem version to 5.5.1.1 and tagged it.
I don't have permissions to push it to RubyGems. Can you pls shoot it? 
The exiting 5.5.1.0 RubyGems version should be yanked as doesn't have 5.5.1 assets (see my previous comment). 
If you want to give me a push access in RubyGems, I'll be happy to take care of it. My email is mehdi@craftsmen.io

**Comment by yllieth** [comment]
Hi @mehlah @arthurzurb! Did you pushed a new version to rubygems?

**Comment by arthurzurb** [comment]
Hey Guys, sorry to get back to you s late, I have pushed this out to
rubygems. Thank you very much for your contribution and patience.

--------------------------------------
Arthur de la Rocha
ZURB | Product Engineer
arthur@ZURB.com <arthur@zurb.com>
www.ZURB.com <http://www.zurb.com/>
Phone: 408.341.0600
------------------------------------------
Code Smarter
http://foundation.zurb.com
------------------------------------------

**Pull request merged**
