### PR TITLE
Remove Old Foundation Files

### PR DESCRIPTION
**Pull request by jessedoyle**
Hi All,

I _think_ this gem may be including some utility JS code from older versions of Foundation.

In [this diff](https://github.com/zurb/foundation-sites/commit/0730b7b4f4495d5c7651fc1ebe63c6a626614dbc#diff-11ba5437268f42332a0ff3914daf8edd), you can see that the `foundation.util.timerAndImageLoader` was split into 2 separate JS files (`timer.js` and `imageLoader.js`).

The most current version of this gem appears to be loading both files [here](https://github.com/zurb/foundation-rails/blob/v6.4.1.3/vendor/assets/js/foundation.js#L9).

It also appears that the same scenario above played out with `foundation.responsiveAccordionTabs.js` (newer) and `foundation.zf.responsiveAccordionTabs.js`.

I believe this was noted in this issue upstream: https://github.com/zurb/foundation-sites/issues/9697.

I took the liberty of updating the version in this PR as a bugfix - please let me know if you wish to do this yourself.

Thanks!

### CODE REVIEW

**Comment by jessedoyle** [comment]
@rafibomb @kball - I just want to bump this as it appears that a number of people are running into this.

In our case, the old JS files are appending a parameter that is blocked by our security appliance.

**Comment by darkodosenovic** [comment]
👍 +1

**Comment by jessedoyle** [comment]
Awesome thanks @ncoden! Sorry about the version bump!

**Comment by ncoden** [comment]
No problem @jessedoyle. Thanks for your contributions.

**Pull request merged**
